### ISSUE TITLE
recommend a book

### ISSUE THREAD

**Issue by flingjie** [lambdaclass/lambdaclass_hacking_learning_path#132]
I think a small book could be added to the readme that aligns with the company's culture: <Mastery: The Keys to Success and Long-Term Fulfillment> by George Leonard.
[Mastery: The Keys to Success and Long-Term Fulfillment](https://a.co/d/iO3gs7v)

**Comment by Loco1982** [comment]
Thanks for pointing this book out! We'll check it and see if we see it fit to add to the learning path.
